Feat: Configure Login UI
CMC-Hackathon-Team1/OnandOff_iOS pull request #8
Opened 2023-01-01 13:33 UTC by e2phus

Login VC Layout 잡기

2023-01-01 15:34 UTC, iosdevSW commented
titleLabel Font는 SystemFont 말고 Notosans Font 으로 변경하면 좋을 것 같습니다.
Then 라이브러리 pods에 추가되어있는데 한 번 이용해보셔도 좋을 것 같아요! 안이용하셔도 되지만요!

2023-01-01 17:00 UTC, iosdevSW requested changes
titleLabel Font는 SystemFont 말고 Notosans Font 으로 변경하면 좋을 것 같습니다.
Then 라이브러리 pods에 추가되어있는데 한 번 이용해보셔도 좋을 것 같아요! 안이용하셔도 되지만요!

2023-01-01 17:00 UTC, iosdevSW commented on OnandOff/ViewController/Authentication/LoginViewController.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 40)
notosans font를 이용하시면 좋을 것 같아요!

`label.font = .notoSans(size: 40, family: .Bold)`

2023-01-01 17:41 UTC, woonkim2022 commented on OnandOff/ViewController/Authentication/LoginViewController.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 40)
저도 같은 의견 입니다! 피그마에 디자이너님이 정해두신 폰트를 사용해야 할 거 같습니다.

2023-01-02 00:35 UTC, e2phus commented on OnandOff/ViewController/Authentication/LoginViewController.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 40)
네 수정하겠습니다 !

2023-01-02 02:21 UTC, iosdevSW approved these changes
Approve

2023-01-02 05:48 UTC, woonkim2022 approved these changes
Approve

2023-01-02 05:50 UTC, merged